apps/agenda/urls.py
from django.urls import path
from . import views

app_name = 'agenda'

urlpatterns = [
    path('<int:pk>/novo/plano/', views.PlanosAdd.as_view(), name='plano_add'),
    path('<int:pk>/atualizar/plano/', views.PlanoUp.as_view(), name='plano_up'),
    path('<int:pk>/deletar/plano/', views.PlanoDEL.as_view(), name='plano_del'),
    path('calendario/', views.OrdemChegadaCalendario.as_view(), name='ordem_chegada_calendario'),
    path('ordem/<int:pk>/fila/', views.ChegadaADD.as_view(), name='chegada_add'),
    path('atualizar/<int:pk>/fila/', views.OrdemChegadaUP.as_view(), name='ordem_chegada_up'),
    path('lista/ordem_fila/', views.OrdemChegadaLista.as_view(), name='ordem_chegada_lista'),
    path('ordem/fila/lista/', views.OrdemChegadaListaData.as_view(), name='ordem_chegada_lista_data'),
    path('pesquisar/atendimento/', views.BuscarOrdem.as_view(), name='pesquisar_agendamento'),
    path('pesquisar/paciente/', views.Buscarpaciente.as_view(), name='pesquisar_paciente'),
    path('buscar/agendamento/', views.buscar_agendamento, name='busca_agendamento'),
    path('buscar/paciente/', views.buscar_paciente, name='busca_paciente'),
    path('agendamentos/<int:pk>/encontrados/', views.AgendamentosEncontrados.as_view(), name='agendamentos_encontrados'),

]

apps/atendimento/urls.py
from django.urls import path
from . import views

app_name = 'atendimento'

urlpatterns = [
    path('<int:pk>/atualizar/', views.OrcamentoUpdate.as_view(), name='orcamento_update'),
    path('financeiro/<int:pk>/atualizar/', views.OrcamentoFinanceiroUpdate.as_view(), name='financeiro_update'),
    path('pagamento/atualizar_status/<int:pk>/', views.AtualizarPagamento.as_view(), name='atualizar_pagamento'),
    path('paciente/<int:pk>/atendimento/', views.Orcamento.as_view(), name='orcamento'),
    path('<int:id>/paciente/<int:pk>/orcamento/', views.OrcamentoOrdem.as_view(), name='ordem_orcamento'),
    path('<int:ordem>/exames-selecionados/<int:pk>/', views.OrcamentoOrdem1.as_view(), name='exames_selecionados'),
    path('lista/', views.OrcamentoLista.as_view(), name='orcamento_lista'),
    path('add_orcamento-exames/', views.add_orcamento_exames, name='add_orcamento_exames'),
    path('pesquisar/', views.Buscaratendimento.as_view(), name='buscar_orcamento'),
    path('buscar/atendimento', views.buscar_atendimento, name='buscar_atendimento'),
    path('visualizar/<int:pk>/atendimento/', views.AtendimentoView.as_view(), name='ver_atendimento'),
    path('<int:pk>/<str:data>/visualizar/', views.AtendimentoView1.as_view(), name='ver_atendimento1'),
    path('etiquetas/<int:pk>/<str:data>/', views.EtiquetasView1.as_view(), name='ver_etiqueta'),
    path('relatorio/diario/', views.RelatorioDiario.as_view(), name='relatorio_diario'),
    path('relatorio/semanal/', views.RelatorioDSemanal.as_view(), name='relatorio_semanal'),
    path('relatorio/periodo/', views.RelatorioPeriodo.as_view(), name='relatorio_periodo'),
    path('ajax/buscar_exames/', views.buscar_exames, name='buscar_exames'),
    path('<int:pk>/<str:data>/<int:atendimento>/comprovante/pdf/', views.criar_comprovante, name='pdf_comprovate'),
]

apps/core/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.Home.as_view(), name='indice'),
    path('sobre/', views.Sobre.as_view(), name='sobre'),
    path('servicos/', views.Servicos.as_view(), name='servicos'),
    path('contato/', views.Contato.as_view(), name='contato'),
    path('blog/', views.Blog.as_view(), name='blog'),
    path('redirecionar/', views.custom_login_redirect, name='redirecione'),
    path('painel/cadastrar/novo/paciente/', views.Cadastrar.as_view(), name='add'),
    path('painel/atualizar/<int:pk>/paciente/', views.AtualizarUser.as_view(), name='add_user'),
    path('painel/cadastrar/novo/funcionario/', views.CadastrarFuncionario.as_view(), name='add_funcionario'),
    path('painel/<int:id>/endereco/', views.EnderecoCad.as_view(), name='endereco'),
    path('painel/administrativo/', views.Painel.as_view(), name='painel'),
    path('painel/lista/pacientes/', views.Pacientes.as_view(), name='pacientes'),
    path('painel/lista/funcionarios/', views.Funcionarios.as_view(), name='funcionarios'),
    path('buscar/atendimento/paciente/', views.BuscarAtendimentoPaciente.as_view(), name='buscar_paciente'),
    path('painel/paciente/<int:pk>/perfil/', views.MostrarPerfil.as_view(), name='perfil'),
    path('paciente/atualizar/<int:pk>/senha/', views.AtualizarSenha.as_view(), name='senha_up'),
    path('painel/atualizar/<int:pk>/paciente/', views.AtualizarPerfil.as_view(), name='atualizar_perfil'),
    path('painel/atualizar/<int:pk>/endereco/', views.AtualizarEndereco.as_view(), name='atualizar_endereco'),
    path('buscar/', views.buscar_atendimento_paciente, name='busca'),
    path('paciente/buscar/', views.buscar_paciente, name='busca_paciente'),
    path('opcoes/<int:pk>/paciente/', views.OpcoesPaciente.as_view(), name='opcoes_paciente'),
    path('opcoes/atendimento/paciente/', views.BuscarOpcoesPaciente.as_view(), name='buscar_opcoes_paciente'),

]

gens/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace='inicio')),
    path('exame/', include('apps.exame.urls', namespace='exame')),
    path('agenda/', include('apps.agenda.urls', namespace='agenda')),
    path('atendimento/', include('apps.atendimento.urls', namespace='atendimento')),
    path('accounts/', include('django.contrib.auth.urls'),),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/agenda/models.py
from django.db import models
from django.utils import timezone

from ..core.models import Usuario


class Plano(models.Model):
    plano = models.CharField(verbose_name='Plano', max_length=150)
    preco = models.DecimalField(verbose_name='Preço', max_digits=5, decimal_places=2, error_messages={'invalid': 'Por favor, insira um preço válido.'})
    habilitado = models.BooleanField(default=False)

    def __str__(self):
        return self.plano

    class Meta:
        verbose_name = 'Plano'
        verbose_name_plural = 'Planos'


class OrdemChegada(models.Model):
    STATUS_ATENDIMENTO = [
        ('AGUARDANDO', 'AGUARDANDO'),
        ('ATENDIDO', 'ATENDIDO'),
        ('CANCELADO', 'CANCELADO'),
    ]
    nome_paciente = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)
    sequencia = models.CharField(max_length=12, unique=True)
    data = models.DateField()
    status_atendido = models.CharField(max_length=15, verbose_name='Atendimento', choices=STATUS_ATENDIMENTO, default='AGUARDANDO')

    class Meta:
        ordering = ['sequencia']

    def save(self, *args, **kwargs):
        if not self.sequencia:  # Se a sequência não estiver definida
            data_hora_atual = timezone.now()
            ano = str(data_hora_atual.year)
            mes = str(data_hora_atual.month).zfill(2)
            dia = str(data_hora_atual.day).zfill(2)
            numero_sequencial = f"{dia}{mes}{ano}"
            # Encontra o último número sequencial para o dia atual
            ultimo_numero_sequencial = OrdemChegada.objects.filter(
                sequencia__startswith=numero_sequencial).order_by('-sequencia').first()
            if ultimo_numero_sequencial:
                ultimo_numero = int(ultimo_numero_sequencial.sequencia[-4:])
                novo_numero = str(ultimo_numero + 1).zfill(4)
                self.sequencia = f"{numero_sequencial}{novo_numero}"
            else:
                self.sequencia = f"{numero_sequencial}0001"

        super().save(*args, **kwargs)

    def __str__(self):
        return self.nome_paciente.nome

    @classmethod
    def fila_dia_aguardando(cls, data):
        return cls.objects.filter(data=data, status_atendido='AGUARDANDO').count()

    @classmethod
    def fila_dia_atendido(cls, data):
        return cls.objects.filter(data=data, status_atendido='ATENDIDO').count()

    @classmethod
    def fila_dia_total(cls, data):
        return cls.objects.filter(data=data).count()

apps/agenda/views.py
import json
from datetime import datetime
from datetime import date
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from .models import Plano, OrdemChegada
from .form import PlanoForm, OrdemChegadaForm, OrdemChegadaUpdateForm
from django.views.generic import CreateView, ListView, UpdateView, TemplateView, DeleteView

from ..core.models import Usuario
from ..exame.models import Exame


class PlanosAdd(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Plano
    form_class = PlanoForm
    success_message = 'Plano adicionado com sucesso!'
    template_name = 'agenda/novo_plano.html'

    def get_success_url(self):
        return reverse_lazy('exame:exame_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        plano = form.save()
        exame = Exame.objects.get(pk=self.kwargs['pk'])
        exame.planos.add(plano)
        exame.save()
        return super().form_valid(form)


class PlanoUp(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Plano
    form_class = PlanoForm
    template_name = 'agenda/plano_up.html'
    success_message = 'Plano atualizado com sucesso!'

    def get_success_url(self):
        return reverse_lazy('exame:exame_detail', kwargs={'pk': self.object.exame.pk})


class PlanoDEL(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Plano
    success_message = 'Plano removido com sucesso!'

    def get_object(self, queryset=None):
       return Plano.objects.get(pk=self.kwargs['pk'])

    def get_success_url(self):
       plano = Plano.objects.get(pk=self.kwargs['pk'])
       exame = Exame.objects.get(planos=plano)
       return reverse_lazy('exame:exame_detail', kwargs={'pk': exame.pk})


class OrdemChegadaCalendario(LoginRequiredMixin, TemplateView):
    template_name = 'agenda/ordem_chegada_data.html'


class ChegadaADD(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = OrdemChegada
    form_class = OrdemChegadaForm
    template_name = 'agenda/ordem_chegada_add.html'
    success_message = 'Adicionada a fila'

    def get_success_url(self):
        return reverse_lazy('agenda:ordem_chegada_lista')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['paciente_pk'] = self.kwargs['pk']
        return kwargs

    def form_valid(self, form):
        ordem = form.save(commit=False)
        paciente = get_object_or_404(Usuario, pk=self.kwargs['pk'])
        ordem.nome_paciente = paciente
        ordem.save()
        return super().form_valid(form)


class OrdemChegadaLista(LoginRequiredMixin, ListView):
    model = OrdemChegada
    template_name = 'agenda/ordem_chegada_lista.html'
    context_object_name = 'ordem_chegada'

    def get_queryset(self):
        return OrdemChegada.objects.filter(data=date.today())

    def get_context_data(self, *, object_list=None, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['data'] = date.today()
        return contexto


class OrdemChegadaListaData(LoginRequiredMixin, TemplateView):
    template_name = 'agenda/ordem_chegada_lista.html'

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        dia = self.request.GET.get("data")
        data1 = datetime.strptime(dia, '%Y-%m-%d')
        data = data1.date()
        atendimentos = OrdemChegada.objects.filter(data=data)
        contexto['ordem_chegada'] = atendimentos
        contexto['data'] = data
        return contexto


class OrdemChegadaUP(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = OrdemChegada
    form_class = OrdemChegadaUpdateForm
    template_name = 'agenda/ordem_chegada_up.html'
    success_message = 'Ordem de chegada alterada!'

    def get_success_url(self):
        return reverse_lazy('agenda:ordem_chegada_lista')


class BuscarOrdem(LoginRequiredMixin, TemplateView):
    template_name = 'agenda/buscar_agendamento.html'


def buscar_agendamento(request):
    if request.POST.get('ajax_request') == 'true':
        res = None
        nomes = request.POST.get('nomes')
        query_se = Usuario.objects.filter(nome__icontains=nomes)

        if len(query_se) > 0 and len(nomes) > 0:
            data = []
            for paciente in query_se:
                item = {
                    'pk': paciente.pk,
                    'nome': paciente.nome,
                    'cpf': paciente.cpf,
                }

                data.append(item)
            res = data
        else:
            res = 'Nenhum paciente encontrado'

        return JsonResponse({'data': res})
    return JsonResponse({})


def buscar_paciente(request):
    if request.POST.get('ajax_request') == 'true':
        res = None
        nomes = request.POST.get('nomes')
        query_se = Usuario.objects.filter(nome__icontains=nomes)

        if len(query_se) > 0 and len(nomes) > 0:
            data = []
            for paciente in query_se:
                retorno = 'CPF não cadastrado'
                if paciente.cpf:
                    retorno = paciente.cpf
                item = {
                    'pk': paciente.pk,
                    'nome': paciente.nome,
                    'cpf': retorno,
                }

                data.append(item)
            res = data
        else:
            res = 'Nenhum paciente encontrado'

        return JsonResponse({'data': res})
    return JsonResponse({})


class AgendamentosEncontrados(LoginRequiredMixin, TemplateView):
    template_name = 'agenda/agendamentos_encontrados.html'

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        paciente = get_object_or_404(Usuario, pk=self.kwargs['pk'])
        agendamentos = OrdemChegada.objects.filter(nome_paciente=paciente)
        contexto['paciente'] = paciente
        contexto['agendamentos'] = agendamentos
        return contexto


class Buscarpaciente(LoginRequiredMixin, TemplateView):
    template_name = 'agenda/buscar_paciente.html'

apps/agenda/templates/agenda/agendamentos_encontrados.html
{% extends 'padrao/painel.html' %}
{% load static %}
{% load bootstrap4 %}
{% block titulo %}
Gen's | Lista de Agendamentos
{% endblock %}
{% block trilha %}
<h4 class="h4 mb-0 text-success font-weight-bold text-uppercase">Agendamentos Encontrados</h4>
{% endblock %}
{% block conteudo %}
<div class="row">
  <div class="col-lg-12">
    <div class="card mb-4">
      <div class="table-responsive p-3">
        <table class="table align-items-center table-flush table-hover" id="dataTableHover">
          <thead class="bg-success">
          <tr class="text-uppercase text-white">
            <th class="text-center">N</th>
            <th>PACIENTE</th>
            <th class="text-center">NUMERO</th>
            <th class="text-center">DATA</th>
            <th class="text-center">STATUS_ATENDIMENTO</th>
          </tr>
          </thead>
          <tbody>
          {% for atendimento in agendamentos %}
            <tr>
            <td class="text-center">{{forloop.counter}}</td>
            <td>
              <a href="{% url 'home:perfil' pk=atendimento.nome_paciente.pk %}" class="text-success text-decoration-none">{{atendimento}}</a>
            </td>
            <td class="text-center">{{atendimento.sequencia}}</td>
            <td class="text-center">{{atendimento.data|date:'d/m/y'}}</td>
              {% if atendimento.status_atendido == 'AGUARDANDO' %}
                <td class="text-center text-primary">{{atendimento.status_atendido}}</td>
              {% elif atendimento.status_atendido == 'ATENDIDO' %}
                <td class="text-center text-success">{{atendimento.status_atendido}}</td>
              {% elif atendimento.status_atendido == 'CANCELADO' %}
                <td class="text-center text-danger">{{atendimento.status_atendido}}</td>
              {% endif %}
          </tr>
          {% empty %}
          <p class="text-danger">Sem atendimentos...</p>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

apps/agenda/templates/agenda/buscar_agendamento.html
{% extends 'padrao/painel.html' %}
{% load static %}
{% load bootstrap4 %}
{% block titulo %}
Gen's | Buscar Agendamento
{% endblock %}
{% block estilo %}
{{block.super}}
<style>
.search:focus{
        background-color: #E8E8E8;
    }
    .result-card {
        width: 50%;
        max-height:auto !important;
        box-shadow: 0 8px 8px 0 rgba(0, 0, 0, 0.25);
        border-radius: 7px;
        border-color: cadetblue;
        padding: 15px 15px;
        margin: auto;
    }
    .not-visible{
        display: none;
    }

    .link{
        text-decoration: none;
    }

    .webseries{
        width: 50px;
        height: 50px;
        border-radius: 50%;
    }
    input[type]{
        border-color:cadetblue!important;
    }
</style>
{% endblock %}
{% block trilha %}
<h4 class="h4 mb-0 text-success font-weight-bold">Buscar Agendamento</h4>
{% endblock %}
{% block conteudo %}
<div class="row">
    <div class="col col-mb-12">
        <div class="card mb-4">
            <div class="card-body">
                <form autocomplete="off" id="search-form" method="post">
                    {% csrf_token %}
                    <input type="text" id="search-input" class="form-control mt-4" placeholder="Pesquisar agendamento pelo nome do paciente...">
                </form>
                <!-- result card-->
                <div id="result-box" class="not-visible">

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
        const sendSearchData = (nomes) => {
            $.ajax({
                type: 'POST',
                url: '{% url "agenda:busca_agendamento" %}',
                data: {
                    'ajax_request': true,
                    'csrfmiddlewaretoken':csrf,
                    'nomes': nomes,
                },
                success: (res) => {
                    const data = res.data
                    if (Array.isArray(data)){
                        result_box.innerHTML = ""
                        //Now display the searched result
                        data.forEach(nomes=> {
                            result_box.innerHTML += `
                                    <a href="/agenda/agendamentos/${nomes.pk}/encontrados/" class='link'>
                                        <div class="row mt-2">
                                            <div class="col-12 text-left ml-3">
                                                <h6>${nomes.nome}</h6>
                                                <h6>${nomes.cpf}</h6>
                                            </div>
                                        </div>
                                    </a>`
                        });
                    }else{
                        if (search_input.value.length > 0){
                             result_box.innerHTML = `<b>${data}</b>`
                        }else{
                            result_box.classList.add('not-visible')
                        }
                    }
                },
                error: (err) => {
                    console.log(err);
                }
            })
        }
        //get search form
        const search_form = document.getElementById('search-form')
        // get search input
        const search_input = document.getElementById('search-input');

        const result_box = document.getElementById('result-box');

        //get csrf token
        const csrf = document.getElementsByName('csrfmiddlewaretoken')[0].value

        search_input.addEventListener('keyup', e=>{
            console.log(e.target.value);

        // Now when key is up show the result box

        if(result_box.classList.contains('not-visible')){
            result_box.classList.remove('not-visible')
        }

        // lets get the search results

        sendSearchData(e.target.value);
        });
    </script>
{% endblock %}

apps/agenda/templates/agenda/buscar_paciente.html
{% extends 'padrao/painel.html' %}
{% load static %}
{% load bootstrap4 %}
{% block titulo %}
Gen's | Buscar Paciente
{% endblock %}
{% block estilo %}
{{block.super}}
<style>
.search:focus{
        background-color: #E8E8E8;
    }
    .result-card {
        width: 50%;
        max-height:auto !important;
        box-shadow: 0 8px 8px 0 rgba(0, 0, 0, 0.25);
        border-radius: 7px;
        border-color: cadetblue;
        padding: 15px 15px;
        margin: auto;
    }
    .not-visible{
        display: none;
    }

    .link{
        text-decoration: none;
    }

    .webseries{
        width: 50px;
        height: 50px;
        border-radius: 50%;
    }
    input[type]{
        border-color:cadetblue!important;
    }
</style>
{% endblock %}
{% block trilha %}
<h4 class="h4 mb-0 text-success font-weight-bold">Buscar Paciente</h4>

{% endblock %}
{% block conteudo %}
<div class="row">
    <div class="col col-mb-12">
        <div class="card mb-4">
            <div class="card-body">
                <div class="">
                    <code>* Pesquise pelo nome do paciente que deseja adicionar a fila</code>
                </div>
                <form autocomplete="off" id="search-form" method="post">
                    {% csrf_token %}
                    <input type="text" id="search-input" class="form-control mt-4" placeholder="Pesquisar paciente...">
                </form>
                <!-- result card-->
                <div id="result-box" class="not-visible">

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
        const sendSearchData = (nomes) => {
            $.ajax({
                type: 'POST',
                url: '{% url "agenda:busca_paciente" %}',
                data: {
                    'ajax_request': true,
                    'csrfmiddlewaretoken':csrf,
                    'nomes': nomes,
                },
                success: (res) => {
                    const data = res.data
                    if (Array.isArray(data)){
                        result_box.innerHTML = ""
                        //Now display the searched result
                        data.forEach(nomes=> {
                            result_box.innerHTML += `
                                    <a href="/agenda/ordem/${nomes.pk}/fila/" class='link'>
                                        <div class="row mt-2">
                                            <div class="col-12 text-left ml-3 text-success">
                                                <h6>${nomes.nome}</h6>
                                                <h6>${nomes.cpf}</h6>
                                            </div>
                                        </div>
                                    </a>`
                        });
                    }else{
                        if (search_input.value.length > 0){
                             result_box.innerHTML = `<b>${data}</b>`
                        }else{
                            result_box.classList.add('not-visible')
                        }
                    }
                },
                error: (err) => {
                    console.log(err);
                }
            })
        }
        //get search form
        const search_form = document.getElementById('search-form')
        // get search input
        const search_input = document.getElementById('search-input');

        const result_box = document.getElementById('result-box');

        //get csrf token
        const csrf = document.getElementsByName('csrfmiddlewaretoken')[0].value

        search_input.addEventListener('keyup', e=>{
            console.log(e.target.value);

        // Now when key is up show the result box

        if(result_box.classList.contains('not-visible')){
            result_box.classList.remove('not-visible')
        }

        // lets get the search results

        sendSearchData(e.target.value);
        });
    </script>
{% endblock %}

apps/agenda/templates/agenda/ordem_chegada_lista.html
{% extends 'padrao/painel.html' %}
{% load static %}
{% load bootstrap4 %}
{% block titulo %}
Gen's | Lista de Atendimentos
{% endblock %}
{% block trilha %}
<h4 class="h4 mb-0 text-success font-weight-bold text-uppercase">ORDEM DE CHEGADA</h4>
<h6 class="h6 mb-0 text-success font-weight-bold text-uppercase"> {{ordem_chegada.0.data}}</h6>
{% endblock %}
{% block conteudo %}
<div class="row">
  <div class="col-lg-12">
    <div class="card mb-4">
      <div class="table-responsive p-3">
        <table class="table align-items-center table-flush table-hover" id="dataTableHover">
          <thead class="bg-success">
          <tr class="text-uppercase text-white">
            <th class="text-center">N</th>
            <th>PACIENTE</th>
            <th class="text-center">NUMERO</th>
            <th class="text-center">DATA</th>
            <th class="text-center">STATUS_ATENDIMENTO</th>
            <th class="text-center">LINKS</th>
          </tr>
          </thead>
          <tbody>
          {% for atendimento in ordem_chegada %}
            <tr>
            <td class="text-center">{{forloop.counter}}</td>
            <td>
              <a href="{% url 'home:perfil' pk=atendimento.nome_paciente.pk %}" class="text-success text-decoration-none">{{atendimento}}</a>
            </td>
            <td class="text-center">{{atendimento.sequencia}}</td>
            <td class="text-center">{{atendimento.data|date:'d/m/y'}}</td>
              {% if atendimento.status_atendido == 'AGUARDANDO' %}
                <td class="text-center text-primary">{{atendimento.status_atendido}}</td>
              {% elif atendimento.status_atendido == 'ATENDIDO' %}
                <td class="text-center text-success">{{atendimento.status_atendido}}</td>
              {% elif atendimento.status_atendido == 'CANCELADO' %}
                <td class="text-center text-danger">{{atendimento.status_atendido}}</td>
              {% endif %}
            <td class="text-center">
              {% if atendimento.status_atendido == 'CANCELADO' %}
              <a href="{% url 'agenda:ordem_chegada_up' pk=atendimento.pk %}" class="text-success" data-toggle="tooltip" data-placement="top" title="Finalizar atendimento">
                <i class="bi bi-pencil"></i>
              </a>
                <i class="bi bi-x text-danger"></i>
              {% elif atendimento.status_atendido == 'ATENDIDO'%}
                <a href="{% url 'atendimento:pdf_comprovate' pk=atendimento.nome_paciente.pk data=data atendimento=atendimento.id %}" class="text-danger" data-toggle="tooltip" data-placement="top" title="Baixar Comprovante">
                  <i class="bi bi-file-pdf"></i>
                </a>
                <a href="{% url 'atendimento:ver_atendimento1' pk=atendimento.nome_paciente.pk data=data %}" class="text-success" data-toggle="tooltip" data-placement="top" title="Visualizar atendimento">
                  <i class="bi bi-eye"></i>
                </a>
                <i class="bi bi-check2-all text-primary"></i>
              {% else %}
              <a href="{% url 'agenda:ordem_chegada_up' pk=atendimento.pk %}" class="text-success" data-toggle="tooltip" data-placement="top" title="Finalizar atendimento">
                <i class="bi bi-pencil"></i>
              </a>
              <a href="{% url 'atendimento:ordem_orcamento' pk=atendimento.nome_paciente.pk id=atendimento.id %}" class="text-primary" data-toggle="tooltip" data-placement="top" title="Fazer orçamento do paciente">
                <i class="bi bi-clipboard2-pulse"></i>
              </a>
              {% endif %}
            </td>
          </tr>
          {% empty %}
          <p class="text-danger">Sem atendimentos...</p>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}