apps/atendimento/urls.py
from django.urls import path
from . import views

app_name = 'atendimento'

urlpatterns = [
    path('<int:pk>/atualizar/', views.OrcamentoUpdate.as_view(), name='orcamento_update'),
    path('financeiro/<int:pk>/atualizar/', views.OrcamentoFinanceiroUpdate.as_view(), name='financeiro_update'),
    path('pagamento/atualizar_status/<int:pk>/', views.AtualizarPagamento.as_view(), name='atualizar_pagamento'),
    path('paciente/<int:pk>/atendimento/', views.Orcamento.as_view(), name='orcamento'),
    path('<int:id>/paciente/<int:pk>/orcamento/', views.OrcamentoOrdem.as_view(), name='ordem_orcamento'),
    path('<int:ordem>/exames-selecionados/<int:pk>/', views.OrcamentoOrdem1.as_view(), name='exames_selecionados'),
    path('lista/', views.OrcamentoLista.as_view(), name='orcamento_lista'),
    path('add_orcamento-exames/', views.add_orcamento_exames, name='add_orcamento_exames'),
    path('pesquisar/', views.Buscaratendimento.as_view(), name='buscar_orcamento'),
    path('buscar/atendimento', views.buscar_atendimento, name='buscar_atendimento'),
    path('visualizar/<int:pk>/atendimento/', views.AtendimentoView.as_view(), name='ver_atendimento'),
    path('<int:pk>/<str:data>/visualizar/', views.AtendimentoView1.as_view(), name='ver_atendimento1'),
    path('etiquetas/<int:pk>/<str:data>/', views.EtiquetasView1.as_view(), name='ver_etiqueta'),
    path('relatorio/diario/', views.RelatorioDiario.as_view(), name='relatorio_diario'),
    path('relatorio/semanal/', views.RelatorioDSemanal.as_view(), name='relatorio_semanal'),
    path('relatorio/periodo/', views.RelatorioPeriodo.as_view(), name='relatorio_periodo'),
    path('ajax/buscar_exames/', views.buscar_exames, name='buscar_exames'),
    path('<int:pk>/<str:data>/<int:atendimento>/comprovante/pdf/', views.criar_comprovante, name='pdf_comprovate'),
]

apps/exame/urls.py
from django.urls import path
from . import views

app_name = 'exame'

urlpatterns = [
    path('adicionar/novo/exame/', views.ExameAdd.as_view(), name='exame_add'),
    path('novo/atendimento/<int:pk>/adicionar/', views.ExameAtendimentoADD.as_view(), name='exame_atendimento_add'),
    path('<int:pk>/atualizar/', views.ExameUp.as_view(), name='exame_up'),
    path('atendimento/<int:pk>/atualizar/', views.ExameAtendimentoUp.as_view(), name='exame_atendimento_update'),
    path('deletar/<int:pk>/', views.ExameDel.as_view(), name='exame_del'),
    path('atendimento/<int:pk>/deletar/', views.ExameAtendimentoDel.as_view(), name='exame_atendimento_del'),
    path('lista/', views.ExamesLista.as_view(), name='exame_list'),
    path('<str:data>/lista/', views.ExamesListaData.as_view(), name='exame_list_data'),
    path('<str:data>/etiquetas/', views.ExamesEtiquetas.as_view(), name='exame_etiquetas'),
    path('aguardando/terceirizados/lista/', views.ExamesListaTerceirizado.as_view(), name='exame_list_terceirizado'),
    path('realizados/<str:data>/', views.ExamesListaDataRealizados.as_view(), name='exame_realizados_data'),
    path('<int:pk>/informacoes/', views.ExameDetalhes.as_view(), name='exame_detail'),
    path('nova/referencias/<int:pk>/', views.ReferenciaADD.as_view(), name='referencias_add'),
    path('referencia/<int:pk>/atualizar/', views.ReferenciaUp.as_view(), name='referencia_update'),
    path('<int:pk>/referencia/deletar/', views.ReferenciaDEL.as_view(), name='referencia_del'),
    path('novo/fator/<int:pk>/adicionar/', views.FatorReferenciaADD.as_view(), name='fator_add'),
    path('fator/atualizar/<int:pk>/', views.FatorUp.as_view(), name='fator_up'),
    path('remover/<int:pk>/fator/', views.FatorDEL.as_view(), name='fator_del'),
    path('novo/valor/<int:pk>/adicionar/', views.ValorEsperadoADD.as_view(), name='padrao_add'),
    path('valor/atualizar/<int:pk>/', views.ValorUp.as_view(), name='valor_up'),
    path('valor/remover/<int:pk>/', views.ValorDEL.as_view(), name='valor_del'),

    # temporario
    path('mostrar/todos/lista/', views.ExamesTodosLista.as_view(), name='exame_todos_lista'),
    path('<int:pk>/pdf/', views.criar_laudo_medico, name='pdf'),
    path('preencher/<int:pk>/folha/', views.preencher_laudo_medico, name='preencher_pdf'),
    path('preencher/grupo/folha/', views.preencher_laudo, name='laudo_pdf'),

    # area medica #
    path('exame/<int:pk>/finalizar/', views.finalizar_exame, name='finalizar_exame'),
    path('area/restrita/<int:pk>/realizar/', views.ExameDetailView.as_view(), name='exame_medico_ver'),
    path('referencia/<int:pk>/salvar/', views.salvar_referencia, name='salvar_referencia'),

    path('terceirizado/area/restrita/<int:pk>/anexar/', views.ExameTerceirizado.as_view(), name='exame_medico_anexar'),
    path('pesquisar/', views.BuscarExame.as_view(), name='pesquisar_exame'),
    path('terceirizado/pesquisar/', views.BuscarExameterceirizado.as_view(), name='pesquisar_exame_terceirizado'),
    path('buscar/exame/', views.buscar_exame, name='buscar_exame'),
    path('terceirizado/buscar/exame/', views.buscar_exame_terceirizado, name='buscar_exame_terceirizado'),
    path('imprimir/etiqueta/<int:pk>/', views.etiqueta_exame, name='etiqueta_exame'),
    path('etiquetas/impressas', views.etiquetas_de_exame, name='etiquetas'),
    #grupo
    path('add/grupo/', views.GrupoCreate.as_view(), name='add_grupo'),
    path('data/grupo/<str:data>/', views.ExamesGrupoData.as_view(), name='grupo_data'),
]

gens/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace='inicio')),
    path('exame/', include('apps.exame.urls', namespace='exame')),
    path('agenda/', include('apps.agenda.urls', namespace='agenda')),
    path('atendimento/', include('apps.atendimento.urls', namespace='atendimento')),
    path('accounts/', include('django.contrib.auth.urls'),),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/atendimento/models.py
from _decimal import Decimal
from django.db import models
from ..core.models import Usuario
from ..exame.models import Exame
from datetime import date


class OrcamentoExames(models.Model):
    FORMA_DE_PAGAMENTO = [
        ('DINHEIRO', 'DINHEIRO'),
        ('CARTAO_CREDITO', 'CARTAO_CREDITO'),
        ('CARTAO_DEBITO', 'CARTAO_DEBITO'),
        ('PIX', 'PIX'),
        ('OUTRO', 'OUTRO'),
    ]
    PAGAMENTO = [
        ('PENDENTE', 'PENDENTE'),
        ('PAGO', 'PAGO'),
    ]
    paciente = models.ForeignKey(Usuario, verbose_name='Paciente', on_delete=models.DO_NOTHING,
                                    related_name='r_paciente')
    exame = models.ManyToManyField(Exame, verbose_name='Exame', related_name='r_exame')
    valor_total = models.DecimalField(verbose_name='Total', max_digits=6, decimal_places=2)
    forma_pagamento = models.CharField(verbose_name='Forma de Pagamento',
                                       max_length=40, choices=FORMA_DE_PAGAMENTO, default='Selecionar')
    pagamento = models.CharField(verbose_name='Pagamento', max_length=20, choices=PAGAMENTO, default='PENDENTE')
    comentario = models.TextField(verbose_name='Observação', null=True, blank=True)
    cancelar = models.BooleanField(default=False)
    data_cadastro = models.DateField(verbose_name='Data Exames', default=date.today)
    data_alterado = models.DateTimeField(verbose_name='Data Modoficação', auto_now=True)


    def calcular_total(self):
        total = Decimal('0.00')
        for exame in self.exame.all():
            plano = exame.planos.first()
            total += plano.preco
        return total

    @classmethod
    def calcular_total_por_data_e_pagamento(cls, data_cadastro, pagamento):
        total = Decimal('0.00')
        orcamentos = cls.objects.filter(data_cadastro=data_cadastro, pagamento=pagamento).order_by('id')
        for orcamento in orcamentos:
            total += orcamento.calcular_total()
        return total, orcamentos

    @classmethod
    def calcular_total_por_periodo(cls, data_inicio, data_fim):
        total = Decimal('0.00')
        if data_inicio == data_fim:
            orcamentos = cls.objects.filter(data_cadastro=data_inicio)
        else:
            orcamentos = cls.objects.filter(data_cadastro__range=(data_inicio, data_fim))

        for orcamento in orcamentos:
            total += orcamento.calcular_total()
        return total, orcamentos

    @classmethod
    def total_atendimentos_diarios(cls):
        return cls.objects.filter(data_cadastro=date.today()).count()

    @classmethod
    def total_atendimentos_semanal(cls):
        return cls.objects.filter(data_cadastro=date.today()).count()

    @classmethod
    def algum_exame_realizado(cls, orcamento):
        return orcamento.exame.filter(status_exame='REALIZADO').exists()

apps/atendimento/forms.py
from django import forms
from django.forms import CheckboxSelectMultiple
from .models import OrcamentoExames, Exame


class OrcamentoForm1(forms.ModelForm):
    planos_selecionados = forms.MultipleChoiceField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = OrcamentoExames
        fields = ['exame', 'forma_pagamento', 'valor_total', 'pagamento', 'comentario']

    def __init__(self, *args, **kwargs):
        exames_selecionados = kwargs.pop('exames_selecionados', None)
        super().__init__(*args, **kwargs)
        if exames_selecionados:
            self.fields['exame'].queryset = Exame.objects.filter(id__in=exames_selecionados)


class OrcamentoForm(forms.ModelForm):
    exames = forms.ModelMultipleChoiceField(
        queryset=Exame.objects.filter(padrao=True).order_by('nome'),
        widget=forms.CheckboxSelectMultiple(),
        required=False,
    )
    planos_selecionados = forms.MultipleChoiceField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = OrcamentoExames
        fields = ['exames', 'forma_pagamento', 'valor_total', 'pagamento', 'comentario']


class OrcamentoFinanceiroForm(forms.ModelForm):
    class Meta:
        model = OrcamentoExames
        fields = ('forma_pagamento', 'valor_total', 'pagamento', 'comentario')


class AtualizarPagamentoForm(forms.ModelForm):
    class Meta:
        model = OrcamentoExames
        fields = ('forma_pagamento', 'valor_total', 'pagamento', 'comentario')


class DateRangeForm(forms.Form):
    data_inicial = forms.DateField(label='Data Inicial', widget=forms.DateInput(attrs={'type': 'date'}))
    data_final = forms.DateField(label='Data Final', widget=forms.DateInput(attrs={'type': 'date'}))

class OrcamentoFormUpdate(forms.ModelForm):
    exames = Exame.objects.filter(padrao=True)
    exame = forms.ModelMultipleChoiceField(
        queryset=exames,
        widget=CheckboxSelectMultiple(),
        required=False,
    )

    nome_paciente_display = forms.CharField(label='Paciente', required=False)

    def __init__(self, *args, **kwargs):
        super(OrcamentoFormUpdate, self).__init__(*args, **kwargs)
        self.fields['nome_paciente_display'].widget.attrs['readonly'] = True
        if self.instance.paciente:
            self.fields['nome_paciente_display'].initial = self.instance.paciente.nome
        exames_associados = self.instance.exame.all()
        self.fields['exame'].queryset = exames_associados

    class Meta:
        model = OrcamentoExames
        fields = ['nome_paciente_display', 'exame', 'forma_pagamento', 'valor_total', 'pagamento', 'comentario']

apps/atendimento/templates/atendimento/atendimento_update.html
{% extends 'padrao/painel.html' %}
{% load static %}
{% load bootstrap4 %}
{% block titulo %}
Gen's | Atualizar Atendimento
{% endblock %}
{% block estilo %}
{{ block.super }}
<style>
    .form-control:focus {
        color: #000;
        background-color: #ffffff;
        border-color: #4cb061;
        outline: 0
    }

.blockquote-footer::before {
    content: ""
}

.info-paciente{
    margin-top: 10px;
}

</style>
{% endblock %}
{% block trilha %}
{% endblock %}
{% block conteudo %}
<div class="row">
    <div class="col col-md-12">
        <div class="card mb-4">
            <div class="card-header" style="margin-bottom: -20px;">
                <h5 class="h4 mb-0 font-weight-bold text-uppercase text-success text-center" style="margin-top: 8px;">Atualizar Atendimento</h5>
                <hr>
                <div class="row justify-content-between ml-1 mr-2">
                    <h6 class="h6 mb-0 font-weight-bold text-uppercase text-success text-left" style="margin-top: 8px;">{{orcamento.paciente}}</h6>
                    <h6 class="h6 mb-0 mt-2 font-weight-bold text-uppercase text-success text-right">{{orcamento.data_cadastro|date:"d/m/Y"}}</h6>
                </div>
                <hr>
                <div class="row">
                    <div id="formato-cpf" class="h6 mb-0 col-6 col-md-6 info-paciente" ></div>
                    <div class="h6 mb-0 col-6 col-md-6 info-paciente">USUARIO:
                        {% if paciente.usuario %}{{paciente.usuario}}{% else %}Não cadastrado{% endif %}
                    </div>
                    <div class="h6 mb-0 col-6 col-md-6 info-paciente">RG: {{orcamento.paciente.rg}}</div>
                    <div class="h6 mb-0 col-6 col-md-6 info-paciente">TELEFONE: {{orcamento.paciente.telefone}}</div>
                    <div class="h6 mb-0 col-6 col-md-6 info-paciente">DATA NASC: {{orcamento.paciente.data_nascimento}}</div>
                    <div class="h6 mb-0 col-6 col-md-6 info-paciente">SEXO: {{orcamento.paciente.sexo}}</div>
                </div>
            </div>
            <div class="card-body">
                <hr>
                <div class="row">
                    {% for exame in orcamento.exame.all %}
                    <div class="col-md-4 ">
                        <div class="card exame-card" style="margin-bottom:10px; margin-top: 10px;">
                            <div class="card-body" style="margin-top:-15px;">
                                <p>
                                <div class="text-success justify-content-between">
                                    <i class="bi bi-check2-circle"></i> <span class="text-uppercase font-weight-bold">{{ exame.nome }}</span>
                                    <div class="float-right">
                                        <a href="{% url 'exame:exame_atendimento_update' pk=exame.pk %}" class="text-success">
                                            <i class="bi bi-pencil"></i>
                                        </a>
                                        <a href="#" class="text-danger" data-toggle="modal" data-target="#exampleModalCenter{{ exame.pk }}">
                                            <i class="bi bi-trash"></i>
                                        </a>
                                        <!-- Modal -->
                                        <div class="modal fade" id="exampleModalCenter{{ exame.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle{{ exame.pk }}" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title font-weight-bold" id="exampleModalLongTitle{{ exame.pk }}">{{ exame.nome }}</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p class="text-dark">Deseja excluir <span class="text-danger">{{ exame.nome }}</span> definitivamente?</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <form method="post" action="{% url 'exame:exame_atendimento_del' pk=exame.pk %}">
                                                            {% csrf_token %}
                                                            <button type="button" class="btn btn-success" data-dismiss="modal">Sair</button>
                                                            <button type="submit" class="btn btn-danger">Excluir</button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                </p>
                                <footer>
                                    {% for plano in exame.planos.all %}
                                    <div class="text-succes">
                                        <i class="bi bi-check2"></i> {{ plano.plano }}<br>
                                        <i class="bi bi-check2"></i> R$ {{plano.preco}}
                                    </div>
                                    {% endfor %}
                                </footer>

                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <p>VAZIO...</p>
                    {% endfor %}
                </div>
                <hr>
                <div class="row">
                    <div class="form-group col-md-4 text-success font-weight-bold">
                        <label>Forma de Pagamento:</label> <br>
                        <span class="font-italic text-secondary font-weight-normal">{{orcamento.forma_pagamento}}</span>
                    </div>
                    <div class="form-group col-md-4 text-success font-weight-bold">
                        <label>Total:</label><br>
                        <span class="font-italic text-secondary font-weight-normal">R$ {{orcamento.valor_total}}</span>
                    </div>
                    <div class="form-group col-md-4 text-success font-weight-bold">
                        <label>Pagamento:</label><br>
                        <span class="font-italic text-secondary font-weight-normal">{{orcamento.pagamento}}</span>
                    </div>
                </div>
                <hr>
                <div class="form-group col-md-12 text-success font-weight-bold">
                        <label>Comentário:</label><br>
                        <span class="font-italic text-secondary font-weight-normal">{{orcamento.comentario}}</span>
                    </div>
                <hr>
                <div class="">
                    <a href="{% url 'exame:exame_atendimento_add' pk=orcamento.pk %}" class="btn btn-success btn-block">Adicionar Exame</a>
                    <a href="{% url 'atendimento:financeiro_update' pk=orcamento.pk %}" class="btn btn-success btn-block">Atualizar Financeiro</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    function formatarCPF(cpf) {
    cpf = cpf.replace(/[.-]/g, '');
    return cpf.slice(0, 3) + '.' + cpf.slice(3, 6) + '.' + cpf.slice(6, 9) + '-' + cpf.slice(9);
}
var cpf = "{{orcamento.paciente.cpf}}";
var cpfFormatado = (cpf == 'None') ? "Não cadastrado" : formatarCPF(cpf);

document.getElementById("formato-cpf").innerText = "CPF: " + cpfFormatado;
</script>
{% endblock %}

apps/atendimento/templates/atendimento/orcamento.html
{% extends 'padrao/painel.html' %}
{% load static %}
{% load bootstrap4 %}

{% block titulo %}
Gen's | Novo Orçamento
{% endblock %}

{% block estilo %}
{{ block.super }}
<style>
    .form-control:focus {
        color: #000;
        background-color: #ffffff;
        border-color: #4cb061;
        outline: 0;
    }
    .blockquote-footer::before {
        content: "";
    }
    .info-paciente {
        margin-top: 10px;
    }
    .exame-card {
        margin-bottom: 10px;
        margin-top: 10px;
    }
    .btn-excluir {
        color: red;
        border: none;
        background: none;
        cursor: pointer;
    }
</style>
{% endblock %}
{% block trilha %}
{% endblock %}
{% block conteudo %}
<div class="row">
    <div class="col-md-12">
        <div class="card mb-4">
            <div class="card-header">
                <h5 class="h5 mb-0 font-weight-bold text-uppercase text-success">{{ paciente }}</h5>
                <hr>
                <div class="row">
                    <div id="formato-cpf" class="h6 mb-0 col-6 info-paciente"></div>
                    <div class="h6 mb-0 col-6 info-paciente">
                        USUARIO: {% if paciente.usuario %}{{ paciente.usuario }}{% else %}Não cadastrado{% endif %}
                    </div>
                    <div class="h6 mb-0 col-6 info-paciente">RG: {{ paciente.rg }}</div>
                    <div class="h6 mb-0 col-6 info-paciente">TELEFONE: {{ paciente.telefone }}</div>
                    <div class="h6 mb-0 col-6 info-paciente">DATA NASC: {{ paciente.data_nascimento }}</div>
                    <div class="h6 mb-0 col-6 info-paciente">SEXO: {{ paciente.sexo }}</div>
                </div>
            </div>
            <hr>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                        <div class="form-group">
                            <h6 class="h6 mb-3 font-weight-bold text-uppercase text-success text-center">Exames Selecionados</h6> <!-- Título adicionado -->
                            <div id="lista_exames_selecionados" class="mb-4 list-group"></div> <!-- Mudança aqui -->
                        </div>
                        <hr>
                        <div class="row">
                            <div class="form-group col-md-4 text-success font-weight-bold">
                                <label for="id_forma_pagamento">Pagamento:</label>
                                <select name="forma_pagamento" id="id_forma_pagamento" class="form-control">
                                    {% for pagamento in form.fields.forma_pagamento.choices %}
                                    <option value="{{ pagamento.0 }}">{{ pagamento.1 }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group col-md-4 text-success font-weight-bold">
                                <label for="id_valor_total">Total:</label>
                                <input type="text" class="form-control" name="valor_total" id="id_valor_total" value="{{ form.initial.valor_total|floatformat:2 }}" readonly>
                            </div>
                            <div class="form-group col-md-4 text-success font-weight-bold">
                                <label for="id_pagamento">Pagamento:</label>
                                <select name="pagamento" id="id_pagamento" class="form-control">
                                    {% for pagamento in form.fields.pagamento.choices %}
                                    <option value="{{ pagamento.0 }}">{{ pagamento.1 }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <hr>
                        <div class="form-group text-success font-weight-bold">
                            <label for="id_comentario">Observação:</label>
                            <textarea name="comentario" id="id_comentario" rows="3" class="form-control">{{ form.initial.comentario }}</textarea>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success btn-block" id="btn_finalizar" disabled>Finalizar</button>
                        </div>
                    </div>
                        <div class="col-md-6">
                        <h6 class="h6 mb-3 font-weight-bold text-uppercase text-success">Exames</h6>
                        <input type="text" id="busca_exames" class="form-control mb-3" placeholder="Buscar exames...">
                            <hr>
                        <div id="lista_exames" class="row">
                            {% for exame in form.exames.field.queryset %}
                            <div class="col-md-12">
                                <div class="card exame-card">
                                    <div class="card-body">
                                        <p>
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" name="exames" id="exame_{{ exame.id }}" value="{{ exame.id }}" onchange="atualizarEstiloCard(this)">
                                                <label class="form-check-label" for="exame_{{ exame.id }}">{{ exame.nome }}</label>
                                            </div>
                                        </p>
                                        <footer>
                                            {% for plano in exame.planos.all %}
                                            <div class="form-check ml-1">
                                                <input class="form-check-input" type="radio" name="exame_{{ exame.id }}_planos" id="exame_{{ exame.id }}_plano_{{ plano.id }}" value="{{ plano.id }}" data-preco="{{ plano.preco|floatformat:2 }}" onchange="atualizarListaExamesSelecionados()" disabled>
                                                <label class="form-check-label" for="exame_{{ exame.id }}_plano_{{ plano.id }}">R$ {{ plano.preco|floatformat:2 }} - {{ plano.plano }}</label>
                                                <input type="hidden" name="planos_selecionados" id="id_planos_selecionados" value="">

                                            </div>
                                            {% endfor %}
                                        </footer>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
document.getElementById('busca_exames').addEventListener('input', function() {
    const busca = this.value.toLowerCase(); // Obtém o texto da busca em minúsculas
    const listaExames = document.getElementById('lista_exames'); // Obtém a lista de exames
    const exames = listaExames.getElementsByClassName('exame-card'); // Obtém todos os cards de exames

    // Itera sobre todos os exames e oculta os que não correspondem à busca
    for (let i = 0; i < exames.length; i++) {
        const nomeExame = exames[i].querySelector('.form-check-label').innerText.toLowerCase(); // Obtém o nome do exame
        if (nomeExame.includes(busca)) {
            exames[i].style.display = ''; // Mostra o exame se corresponder à busca
        } else {
            exames[i].style.display = 'none'; // Oculta o exame se não corresponder
        }
    }
});


    function atualizarListaExamesSelecionados() {
        var lista = document.getElementById('lista_exames_selecionados');
        lista.innerHTML = ''; // Limpa a lista
        var total = 0; // Inicializa o total
        var planosSelecionados = []; // Array para armazenar os planos selecionados
        var checkboxes = document.querySelectorAll('input[name^="exames"]:checked');

        checkboxes.forEach(function(checkbox) {
            var exameId = checkbox.value;
            var planoSelecionadoExame = document.querySelector('input[name="exame_' + exameId + '_planos"]:checked');
            if (planoSelecionadoExame) {
                var precoStr = planoSelecionadoExame.getAttribute('data-preco').replace(',', '.');
                var preco = parseFloat(precoStr);
                var nomeExame = document.querySelector('label[for="exame_' + exameId + '"]').innerText;
                lista.innerHTML += `
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    ${nomeExame}: R$ ${preco.toFixed(2)}
                    <button class="btn-excluir" onclick="removerExame('${exameId}')">
                        <i class="bi bi-x-circle-fill"></i>
                    </button>
                </li>`;
                total += preco; // Atualiza o total
                planosSelecionados.push(planoSelecionadoExame.value); // Adiciona o plano selecionado
        }
    });

    // Atualiza o valor do campo oculto com os IDs dos planos selecionados
    document.getElementById('id_planos_selecionados').value = planosSelecionados.join(',');

    document.getElementById('id_valor_total').value = total.toFixed(2); // Atualiza o valor total
    document.getElementById('btn_finalizar').disabled = planosSelecionados.length === 0; // Habilita ou desabilita o botão "Finalizar"
}


    function removerExame(exameId) {
        var checkbox = document.getElementById('exame_' + exameId);
        checkbox.checked = false; // Desmarcar o checkbox
        atualizarEstiloCard(checkbox); // Atualizar o estilo do card
        atualizarListaExamesSelecionados(); // Atualizar a lista
    }

    function atualizarEstiloCard(checkbox) {
        var card = checkbox.closest('.exame-card');
        var titulo = card.querySelector('.form-check-label');
        if (checkbox.checked) {
            card.style.border = '2px solid #4cb061';
            titulo.style.color = '#4cb061';
            ativarPlanos(checkbox);
        } else {
            card.style.border = '2px solid transparent';
            titulo.style.color = '';
            desativarPlanos(checkbox);
        }
        atualizarListaExamesSelecionados(); // Atualiza a lista de exames selecionados
    }

    function ativarPlanos(checkbox) {
        var checkboxes = checkbox.closest('.exame-card').querySelectorAll('.form-check-input[type="radio"]');
        checkboxes.forEach(function(cb) {
            cb.disabled = !checkbox.checked;
            cb.checked = false; // Desmarcar todos planos ao ativar checkbox
        });
    }

    function desativarPlanos(checkbox) {
        var checkboxes = checkbox.closest('.exame-card').querySelectorAll('.form-check-input[type="radio"]');
        checkboxes.forEach(function(cb) {
            cb.disabled = true;
        });
    }



</script>
{% endblock %}