apps/agenda/urls.py
from django.urls import path
from . import views

app_name = 'agenda'

urlpatterns = [
    path('<int:pk>/novo/plano/', views.PlanosAdd.as_view(), name='plano_add'),
    path('<int:pk>/atualizar/plano/', views.PlanoUp.as_view(), name='plano_up'),
    path('<int:pk>/deletar/plano/', views.PlanoDEL.as_view(), name='plano_del'),
    path('calendario/', views.OrdemChegadaCalendario.as_view(), name='ordem_chegada_calendario'),
    path('ordem/<int:pk>/fila/', views.ChegadaADD.as_view(), name='chegada_add'),
    path('atualizar/<int:pk>/fila/', views.OrdemChegadaUP.as_view(), name='ordem_chegada_up'),
    path('lista/ordem_fila/', views.OrdemChegadaLista.as_view(), name='ordem_chegada_lista'),
    path('ordem/fila/lista/', views.OrdemChegadaListaData.as_view(), name='ordem_chegada_lista_data'),
    path('pesquisar/atendimento/', views.BuscarOrdem.as_view(), name='pesquisar_agendamento'),
    path('pesquisar/paciente/', views.Buscarpaciente.as_view(), name='pesquisar_paciente'),
    path('buscar/agendamento/', views.buscar_agendamento, name='busca_agendamento'),
    path('buscar/paciente/', views.buscar_paciente, name='busca_paciente'),
    path('agendamentos/<int:pk>/encontrados/', views.AgendamentosEncontrados.as_view(), name='agendamentos_encontrados'),

]

apps/atendimento/urls.py
from django.urls import path
from . import views

app_name = 'atendimento'

urlpatterns = [
    path('<int:pk>/atualizar/', views.OrcamentoUpdate.as_view(), name='orcamento_update'),
    path('financeiro/<int:pk>/atualizar/', views.OrcamentoFinanceiroUpdate.as_view(), name='financeiro_update'),
    path('pagamento/atualizar_status/<int:pk>/', views.AtualizarPagamento.as_view(), name='atualizar_pagamento'),
    path('paciente/<int:pk>/atendimento/', views.Orcamento.as_view(), name='orcamento'),
    path('<int:id>/paciente/<int:pk>/orcamento/', views.OrcamentoOrdem.as_view(), name='ordem_orcamento'),
    path('<int:ordem>/exames-selecionados/<int:pk>/', views.OrcamentoOrdem1.as_view(), name='exames_selecionados'),
    path('lista/', views.OrcamentoLista.as_view(), name='orcamento_lista'),
    path('add_orcamento-exames/', views.add_orcamento_exames, name='add_orcamento_exames'),
    path('pesquisar/', views.Buscaratendimento.as_view(), name='buscar_orcamento'),
    path('buscar/atendimento', views.buscar_atendimento, name='buscar_atendimento'),
    path('visualizar/<int:pk>/atendimento/', views.AtendimentoView.as_view(), name='ver_atendimento'),
    path('<int:pk>/<str:data>/visualizar/', views.AtendimentoView1.as_view(), name='ver_atendimento1'),
    path('etiquetas/<int:pk>/<str:data>/', views.EtiquetasView1.as_view(), name='ver_etiqueta'),
    path('relatorio/diario/', views.RelatorioDiario.as_view(), name='relatorio_diario'),
    path('relatorio/semanal/', views.RelatorioDSemanal.as_view(), name='relatorio_semanal'),
    path('relatorio/periodo/', views.RelatorioPeriodo.as_view(), name='relatorio_periodo'),
    path('ajax/buscar_exames/', views.buscar_exames, name='buscar_exames'),
    path('<int:pk>/<str:data>/<int:atendimento>/comprovante/pdf/', views.criar_comprovante, name='pdf_comprovate'),
]

apps/exame/urls.py
from django.urls import path
from . import views

app_name = 'exame'

urlpatterns = [
    path('adicionar/novo/exame/', views.ExameAdd.as_view(), name='exame_add'),
    path('novo/atendimento/<int:pk>/adicionar/', views.ExameAtendimentoADD.as_view(), name='exame_atendimento_add'),
    path('<int:pk>/atualizar/', views.ExameUp.as_view(), name='exame_up'),
    path('atendimento/<int:pk>/atualizar/', views.ExameAtendimentoUp.as_view(), name='exame_atendimento_update'),
    path('deletar/<int:pk>/', views.ExameDel.as_view(), name='exame_del'),
    path('atendimento/<int:pk>/deletar/', views.ExameAtendimentoDel.as_view(), name='exame_atendimento_del'),
    path('lista/', views.ExamesLista.as_view(), name='exame_list'),
    path('<str:data>/lista/', views.ExamesListaData.as_view(), name='exame_list_data'),
    path('<str:data>/etiquetas/', views.ExamesEtiquetas.as_view(), name='exame_etiquetas'),
    path('aguardando/terceirizados/lista/', views.ExamesListaTerceirizado.as_view(), name='exame_list_terceirizado'),
    path('realizados/<str:data>/', views.ExamesListaDataRealizados.as_view(), name='exame_realizados_data'),
    path('<int:pk>/informacoes/', views.ExameDetalhes.as_view(), name='exame_detail'),
    path('nova/referencias/<int:pk>/', views.ReferenciaADD.as_view(), name='referencias_add'),
    path('referencia/<int:pk>/atualizar/', views.ReferenciaUp.as_view(), name='referencia_update'),
    path('<int:pk>/referencia/deletar/', views.ReferenciaDEL.as_view(), name='referencia_del'),
    path('novo/fator/<int:pk>/adicionar/', views.FatorReferenciaADD.as_view(), name='fator_add'),
    path('fator/atualizar/<int:pk>/', views.FatorUp.as_view(), name='fator_up'),
    path('remover/<int:pk>/fator/', views.FatorDEL.as_view(), name='fator_del'),
    path('novo/valor/<int:pk>/adicionar/', views.ValorEsperadoADD.as_view(), name='padrao_add'),
    path('valor/atualizar/<int:pk>/', views.ValorUp.as_view(), name='valor_up'),
    path('valor/remover/<int:pk>/', views.ValorDEL.as_view(), name='valor_del'),

    # temporario
    path('mostrar/todos/lista/', views.ExamesTodosLista.as_view(), name='exame_todos_lista'),
    path('<int:pk>/pdf/', views.criar_laudo_medico, name='pdf'),
    path('preencher/<int:pk>/folha/', views.preencher_laudo_medico, name='preencher_pdf'),
    path('preencher/grupo/folha/', views.preencher_laudo, name='laudo_pdf'),

    # area medica #
    path('exame/<int:pk>/finalizar/', views.finalizar_exame, name='finalizar_exame'),
    path('area/restrita/<int:pk>/realizar/', views.ExameDetailView.as_view(), name='exame_medico_ver'),
    path('referencia/<int:pk>/salvar/', views.salvar_referencia, name='salvar_referencia'),

    path('terceirizado/area/restrita/<int:pk>/anexar/', views.ExameTerceirizado.as_view(), name='exame_medico_anexar'),
    path('pesquisar/', views.BuscarExame.as_view(), name='pesquisar_exame'),
    path('terceirizado/pesquisar/', views.BuscarExameterceirizado.as_view(), name='pesquisar_exame_terceirizado'),
    path('buscar/exame/', views.buscar_exame, name='buscar_exame'),
    path('terceirizado/buscar/exame/', views.buscar_exame_terceirizado, name='buscar_exame_terceirizado'),
    path('imprimir/etiqueta/<int:pk>/', views.etiqueta_exame, name='etiqueta_exame'),
    path('etiquetas/impressas', views.etiquetas_de_exame, name='etiquetas'),
    #grupo
    path('add/grupo/', views.GrupoCreate.as_view(), name='add_grupo'),
    path('data/grupo/<str:data>/', views.ExamesGrupoData.as_view(), name='grupo_data'),
]

gens/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace='inicio')),
    path('exame/', include('apps.exame.urls', namespace='exame')),
    path('agenda/', include('apps.agenda.urls', namespace='agenda')),
    path('atendimento/', include('apps.atendimento.urls', namespace='atendimento')),
    path('accounts/', include('django.contrib.auth.urls'),),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/exame/views.py
import json
import textwrap
from io import BytesIO
from urllib.parse import unquote

import requests
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, TemplateView
from reportlab.lib.colors import Color
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4, letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from ..agenda.models import Plano
from ..atendimento.models import OrcamentoExames
from ..core.models import Usuario
from ..exame.exame_create import objeto_exame
from ..exame.forms import *
from ..exame.models import Exame, ReferenciaExame, FatoresReferencia, ValorEsperado, GrupoExame
from ..exame.relatorio import desenhar_retangulo, adicionar_linha_paralela, adicionar_linha_vertical, escrever_texto, \
    escrever_dados_clinica, escrever_exame_info, configurar_margens


class ExameAdd(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = ExameForm
    template_name = 'exame/exame_add.html'
    success_message = 'Exame cadastrado com sucesso!'

    def get_success_url(self):
        return reverse_lazy('exame:exame_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        exame = form.save(commit=False)
        exame.padrao = True
        exame.save()
        return super().form_valid(form)


class ExameAtendimentoADD(LoginRequiredMixin, SuccessMessageMixin,  CreateView):
    model = Exame
    form_class = ExameAtendimentoForm
    template_name = 'exame/exame_atendimento_add.html'
    success_message = 'Exame adicionado ao atendimento'

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        orcamento = OrcamentoExames.objects.get(pk=self.kwargs['pk'])
        contexto['orcamento'] = orcamento
        return contexto

    def form_valid(self, form):
        # Execute sua lógica de salvar exame aqui
        orcamento = get_object_or_404(OrcamentoExames, pk=self.kwargs['pk'])
        with transaction.atomic():
            exames_selecionados_ids = self.request.POST.getlist('exames')
            planos_selecionados = self.request.POST.getlist('planos_selecionados')
            planos = [plano for plano in planos_selecionados if plano]
            numeros = []
            for plano in planos:
                numeros.extend(map(int, plano.split(',')))

            print(f'Numeros: {numeros}')

            for numero in exames_selecionados_ids:
                id = int(numero)
                obj_exame = objeto_exame(pk=id, sequencia=numeros)
                orcamento.exame.add(obj_exame)
            orcamento.valor_total = orcamento.calcular_total()
            orcamento.save()

        messages.success(self.request, self.success_message)
        url = reverse_lazy('atendimento:orcamento_update', kwargs={'pk': orcamento.pk})
        return HttpResponseRedirect(url)


class ExamesLista(LoginRequiredMixin, ListView):
    model = Exame
    template_name = 'exame/exames_lista.html'
    context_object_name = 'exames'

    def get_queryset(self):
        return Exame.objects.filter(ativo=True, padrao=True).order_by('nome')


class ExamesListaData(LoginRequiredMixin, ListView):
    model = Exame
    template_name = 'exame/exames_lista_data.html'
    context_object_name = 'exames'

    def get_queryset(self):
        data = self.kwargs['data']
        return Exame.objects.filter(data_cadastro__date=data, status_exame='AGUARDANDO', padrao=False, terceirizado=False)

    def get_context_data(self, *, object_list=None, **kwargs):
        contexto = super().get_context_data(**kwargs)
        data = self.kwargs['data']
        contexto['terceirizados'] = Exame.objects.filter(data_cadastro__date=data, status_exame='AGUARDANDO', padrao=False, terceirizado=True)
        return contexto


class ExamesEtiquetas(LoginRequiredMixin, ListView):
    model = Exame
    template_name = 'exame/exames_etiquetas.html'
    context_object_name = 'exames'

    def get_queryset(self):
        data = self.kwargs['data']
        return Exame.objects.filter(data_cadastro__date=data, status_exame='AGUARDANDO', padrao=False)

    def get_context_data(self, *, object_list=None, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['data'] = self.kwargs['data']
        return contexto


class ExamesGrupoData(LoginRequiredMixin, ListView):
    model = Exame
    template_name = 'exame/exames_grupo_data.html'
    context_object_name = 'exames'

    def get_queryset(self):
        data = self.kwargs['data']
        return Exame.objects.filter(data_cadastro__date=data, status_exame='AGUARDANDO', padrao=False, terceirizado=False)

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        exames = self.get_queryset()
        grupos = GrupoExame.objects.all()

        grupos_exames = {}  # Dicionário para armazenar {grupo: ids_dos_exames}

        for grupo in grupos:
            exames_do_grupo = grupo.exames.all()
            exames_ids = [exame.id for exame in exames if exame.nome in exames_do_grupo.values_list('nome', flat=True)]

            if exames_ids:
                grupos_exames[grupo.nome] = exames_ids  # Apenas os IDs dos exames

        exames_sem_grupo = []
        for exame in exames:
            # Verifica se o nome do exame não pertence a nenhum grupo
            pertence_a_grupo = False
            for grupo in grupos:
                exames_do_grupo = grupo.exames.all()
                if exame.nome in exames_do_grupo.values_list('nome', flat=True):
                    pertence_a_grupo = True
                    break
            if not pertence_a_grupo:
                exames_sem_grupo.append(exame.id)

        # Adiciona os exames sem grupo ao dicionário
        if exames_sem_grupo:
            grupos_exames['Sem Grupo'] = exames_sem_grupo

        contexto['grupos'] = grupos_exames  # Passa apenas os IDs para o template
        return contexto


class ExamesListaTerceirizado(LoginRequiredMixin, ListView):
    model = Exame
    template_name = 'exame/exames_lista_terceirizado.html'
    context_object_name = 'exames'

    def get_queryset(self):
        return Exame.objects.filter(status_exame='AGUARDANDO', padrao=False, terceirizado=True)


class ExamesListaDataRealizados(LoginRequiredMixin, ListView):
    model = Exame
    template_name = 'exame/exames_realizados_data.html'
    context_object_name = 'exames'

    def get_queryset(self):
        data = self.kwargs['data']
        return Exame.objects.filter(data_cadastro__date=data, status_exame='REALIZADO')


class ExameUp(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Exame
    form_class = ExameForm
    template_name = 'exame/exame_up.html'
    success_message = 'Exame atualizado com sucesso!'

    def get_success_url(self):
        return reverse_lazy('exame:exame_detail', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        exame = Exame.objects.get(pk=self.kwargs['pk'])
        contexto['exame'] = exame
        return contexto


class ExameAtendimentoUp(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Exame
    fields = ()
    template_name = 'exame/exame_atendimento_up.html'
    success_message = 'Exame atualizado com sucesso!'

    def get_success_url(self):
        exame = self.get_object()
        orcamento = OrcamentoExames.objects.filter(exame=exame).first()
        return reverse_lazy('atendimento:orcamento_update', kwargs={'pk': orcamento.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        exame = self.get_object()
        orcamento = OrcamentoExames.objects.filter(exame=exame).first()
        exame1 = ''
        exames = Exame.objects.filter(ativo=True, padrao=True)
        for exam in exames:
            if exam.nome == exame.nome:
                exame1 = exam

        context['exame'] = exame1
        context['orcamento'] = orcamento
        return context

    def form_valid(self, form):
        exame = form.save(commit=False)
        plano_selecionado_id = self.request.POST.get('plano_selecionado')
        plano = Plano.objects.get(pk=plano_selecionado_id)
        plano_create = Plano.objects.create(
            plano=plano.plano,
            preco=plano.preco,
            habilitado=True
        )
        plano1 = exame.planos.first()
        plano1.delete()

        exame.planos.add(plano_create)
        orcamento = OrcamentoExames.objects.filter(exame=exame).first()
        orcamento.valor_total = orcamento.calcular_total()
        orcamento.save()
        return super().form_valid(form)


class ExameDetalhes(LoginRequiredMixin, DetailView):
    model = Exame
    template_name = 'exame/exame_detalhes.html'
    context_object_name = 'exame'

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        exame = Exame.objects.get(pk=self.kwargs['pk'], ativo=True)
        contexto['exame'] = exame
        return contexto


class ExameDel(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Exame
    success_message = 'Exame padrão removido com sucesso.'

    def get_object(self, queryset=None):
        return Exame.objects.get(pk=self.kwargs['pk'])

    def get_success_url(self):
        return reverse_lazy('exame:exame_list')

apps/exame/templates/exame/exame_add.html
{% extends 'padrao/painel.html' %}
{% load static %}
{% load bootstrap4 %}
{% block titulo %}
Gen's | Novo Exame
{% endblock %}
{% block estilo %}
{{block.super}}
<style>
    .form-control:focus {
    color: #000;
    background-color: #ffffff;
    border-color: #4cb061;
    outline: 0
}
</style>
{% endblock %}
{% block trilha %}
<h4 class="h4 mb-0 text-success font-weight-bold">NOVO EXAME</h4>
{% endblock %}
{% block conteudo %}
<div class="row">
    <div class="col col-mb-12">
        <div class="card mb-4">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="form-group">
                        <button type="submit" class="btn btn-success btn-block">Cadastrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/exame/templates/exame/exame_detalhes.html
{% extends 'padrao/painel.html' %}
{% load static %}
{% load bootstrap4 %}
{% block titulo %}
Gen's | Info Exame
{% endblock %}
{% block trilha %}
<h4 class="h4 mb-0 text-success font-weight-bold text-uppercase">{{exame}}</h4>
{% endblock %}
{% block conteudo %}
<div class="row mb-3">
    <div class="col-xl-12 col-lg-12 mb-4">
        <div class="card">
            <div class="card-header py-4 bg-success d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-white">INFORMAÇÔES BÁSICAS</h6>
            </div>
            <div>
                <div class="customer-message align-items-center">
                    <a class="font-weight-bold" href="#">
                        <div class="text-success message-title">Nome</div>
                        <div class="small text-gray-500 message-time font-weight-bold">{{exame}}</div>
                    </a>
                </div>
                <div class="customer-message align-items-center">
                    <a class="font-weight-bold" href="#">
                        <div class="text-success message-title">Material Coletado</div>
                        <div class="small text-gray-500 message-time font-weight-bold">{{exame.material}}</div>
                    </a>
                </div>
                <div class="customer-message align-items-center">
                    <a class="font-weight-bold" href="#">
                        <div class="text-success message-title">Metódo de Análise</div>
                        <div class="small text-gray-500 message-time font-weight-bold">{{exame.metodo}}</div>
                    </a>
                </div>
                <div class="card-footer text-center">
                    <a class="m-0 small text-success card-link font-weight-bold" href="{% url 'exame:exame_up' pk=exame.pk %}">Editar Informações Básicas <i
                            class="fas fa-chevron-right"></i></a>
                </div>
            </div>
        </div>
    </div>
    {% if exame.terceirizado %}
    {% else %}
        <div class="col-xl-8 col-lg-7 mb-4">
        <div class="card">
            <div class="card-header py-4 bg-success d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-white">REFERÊNCIAS</h6>
            </div>
            {% for referencia in exame.referencias.all %}
            <div class="customer-message align-items-center d-flex justify-content-between">
                <a class="font-weight-bold" href="#">
                    <div class="text-success message-title">{{referencia.nome_referencia}}</div>
                    {% if referencia.fator %}
                        {% for fator_ref in referencia.fatores.all %}
                            <div class="small text-gray-500 message-time font-weight-bold">
                               {% if fator_ref.nome_fator != None %}{{fator_ref.nome_fator}}{% elif  fator_ref.idade != None %}
                                {{fator_ref.idade}}{% else %}Sem fator de referência{% endif %}:
                                {% if  fator_ref.limite_inferior %}{{fator_ref.limite_inferior}} a {{fator_ref.limite_superior}}
                                {% else %}{{fator_ref.limite_superior}}{% endif %}
                           </div>
                        {% endfor %}
                    {% endif %}
                    {% if referencia.esperado %}
                        {% for value1 in referencia.padrao.all %}
                            <div class="small text-gray-500 message-time font-weight-bold">
                              {{value1.tipo_valor}}: {{value1.valor_esperado}}
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% if referencia.esperado == False and referencia.fator == False %}
                       <div class="small text-gray-500 message-time font-weight-bold">
                           {% if  referencia.limite_inferior != None and referencia.limite_superior != Nome %}
                            {{referencia.limite_inferior}} a {{referencia.limite_superior}}
                           {% else %}
                              Adicione Valores de Referência
                           {% endif %}

                       </div>
                    {% endif %}
                </a>
                <div class="small text-gray-500 message-time font-weight-bold ml-auto"style="margin-right:30px;">
                    <a href="{% url 'exame:referencia_update' pk=referencia.pk %}" class="text-success"><i class="bi bi-pencil-square"></i></a>
                    <a href="#" class="text-danger" type="button" data-toggle="modal" data-target="#exampleModalCenter{{referencia.id}}"
                       id="#modalCenter{{referencia.id}}"><i class="bi bi-trash"></i></a>
                </div>
            </div>
            <div class="modal fade" id="exampleModalCenter{{referencia.id}}" tabindex="-1" role="dialog"
                 aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header bg-danger">
                            <h5 class="modal-title text-white" id="exampleModalCenterTitle">{{referencia.nome_referencia}}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Deseja realmente deletar <strong class="text-danger">{{referencia.nome_referencia}}</strong> ?<br>
                            <span class="small">Todos os valores a respeito de {{referencia.nome_referencia}} serão excluídos!</span>
                        </div>
                        <div class="modal-footer">
                            <form method="post" action="{% url 'exame:referencia_del' pk=referencia.pk %}">
                                {% csrf_token %}
                                <button type="button" class="btn btn-outline-success" data-dismiss="modal">Sair</button>
                                <button type="submit" class="btn btn-outline-danger">Confirmar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="customer-message align-items-center">
                <a class="font-weight-bold" href="#">
                    <div class="text-success message-title">Sem referências</div>
                    <div class="small text-gray-500 message-time font-weight-bold">Sem referências</div>
                </a>
            </div>
            {% endfor %}
            <div class="card-footer text-center">
                <a class="m-0 small text-success card-link font-weight-bold" href="{% url 'exame:referencias_add' pk=exame.pk %}">Nova Referência <i class="fas fa-chevron-right"></i></a>
            </div>

        </div>
    </div>
    {% endif %}
    <div class="col-xl-4 col-lg-5 mb-4">
        <div class="card">
            <div class="card-header py-4 bg-success d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-white">PLANOS</h6>
            </div>
            <div>
                {% for plano in exame.planos.all %}
                <div class="customer-message align-items-center d-flex justify-content-between">
                    <a class="font-weight-bold" href="#">
                        <div class="text-success message-title">{{plano}}</div>
                        <div class="small text-gray-500 message-time font-weight-bold">R$ {{plano.preco}}</div>
                    </a>
                <div class="small text-gray-500 message-time font-weight-bold ml-auto"style="margin-right:30px;">
                    <a href="{% url 'agenda:plano_up' pk=plano.pk %}" class="text-success"><i class="bi bi-pencil-square"></i></a>
                    <a href="#" class="text-danger" type="button" data-toggle="modal" data-target="#exampleModalCenter{{plano.id}}"
                       id="#modalCenter{{plano.id}}"><i class="bi bi-trash"></i></a>
                </div>
                </div>
                <div class="modal fade" id="exampleModalCenter{{plano.id}}" tabindex="-1" role="dialog"
                 aria-labelledby="exampleModalCenterTitlePlano" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header bg-danger">
                            <h5 class="modal-title text-white" id="exampleModalCenterTitlePlano">{{plano}}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Deseja realmente deletar <strong class="text-danger">{{plano}}</strong> ?<br>
                        </div>
                        <div class="modal-footer">
                            <form method="post" action="{% url 'agenda:plano_del' pk=plano.pk %}">
                                {% csrf_token %}
                                <button type="button" class="btn btn-outline-success" data-dismiss="modal">Sair</button>
                                <button type="submit" class="btn btn-outline-danger">Confirmar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
                {% empty %}
                <div class="customer-message align-items-center">
                    <a class="font-weight-bold" href="{% url 'agenda:plano_add' pk=exame.pk %}">
                        <div class="text-success message-title">Adicione os planos</div>
                        <div class="small text-gray-500 message-time font-weight-bold"></div>
                    </a>
                </div>
                {% endfor %}
                <div class="card-footer text-center">
                    <a class="m-0 small text-success card-link font-weight-bold" href="{% url 'agenda:plano_add' pk=exame.pk %}">Adicionar Plano <i
                            class="fas fa-chevron-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}