apps/agenda/urls.py
from django.urls import path
from . import views

app_name = 'agenda'

urlpatterns = [
    path('<int:pk>/novo/plano/', views.PlanosAdd.as_view(), name='plano_add'),
    path('<int:pk>/atualizar/plano/', views.PlanoUp.as_view(), name='plano_up'),
    path('<int:pk>/deletar/plano/', views.PlanoDEL.as_view(), name='plano_del'),
    path('calendario/', views.OrdemChegadaCalendario.as_view(), name='ordem_chegada_calendario'),
    path('ordem/<int:pk>/fila/', views.ChegadaADD.as_view(), name='chegada_add'),
    path('atualizar/<int:pk>/fila/', views.OrdemChegadaUP.as_view(), name='ordem_chegada_up'),
    path('lista/ordem_fila/', views.OrdemChegadaLista.as_view(), name='ordem_chegada_lista'),
    path('ordem/fila/lista/', views.OrdemChegadaListaData.as_view(), name='ordem_chegada_lista_data'),
    path('pesquisar/atendimento/', views.BuscarOrdem.as_view(), name='pesquisar_agendamento'),
    path('pesquisar/paciente/', views.Buscarpaciente.as_view(), name='pesquisar_paciente'),
    path('buscar/agendamento/', views.buscar_agendamento, name='busca_agendamento'),
    path('buscar/paciente/', views.buscar_paciente, name='busca_paciente'),
    path('agendamentos/<int:pk>/encontrados/', views.AgendamentosEncontrados.as_view(), name='agendamentos_encontrados'),

]

apps/atendimento/urls.py
from django.urls import path
from . import views

app_name = 'atendimento'

urlpatterns = [
    path('<int:pk>/atualizar/', views.OrcamentoUpdate.as_view(), name='orcamento_update'),
    path('financeiro/<int:pk>/atualizar/', views.OrcamentoFinanceiroUpdate.as_view(), name='financeiro_update'),
    path('pagamento/atualizar_status/<int:pk>/', views.AtualizarPagamento.as_view(), name='atualizar_pagamento'),
    path('paciente/<int:pk>/atendimento/', views.Orcamento.as_view(), name='orcamento'),
    path('<int:id>/paciente/<int:pk>/orcamento/', views.OrcamentoOrdem.as_view(), name='ordem_orcamento'),
    path('<int:ordem>/exames-selecionados/<int:pk>/', views.OrcamentoOrdem1.as_view(), name='exames_selecionados'),
    path('lista/', views.OrcamentoLista.as_view(), name='orcamento_lista'),
    path('add_orcamento-exames/', views.add_orcamento_exames, name='add_orcamento_exames'),
    path('pesquisar/', views.Buscaratendimento.as_view(), name='buscar_orcamento'),
    path('buscar/atendimento', views.buscar_atendimento, name='buscar_atendimento'),
    path('visualizar/<int:pk>/atendimento/', views.AtendimentoView.as_view(), name='ver_atendimento'),
    path('<int:pk>/<str:data>/visualizar/', views.AtendimentoView1.as_view(), name='ver_atendimento1'),
    path('etiquetas/<int:pk>/<str:data>/', views.EtiquetasView1.as_view(), name='ver_etiqueta'),
    path('relatorio/diario/', views.RelatorioDiario.as_view(), name='relatorio_diario'),
    path('relatorio/semanal/', views.RelatorioDSemanal.as_view(), name='relatorio_semanal'),
    path('relatorio/periodo/', views.RelatorioPeriodo.as_view(), name='relatorio_periodo'),
    path('ajax/buscar_exames/', views.buscar_exames, name='buscar_exames'),
    path('<int:pk>/<str:data>/<int:atendimento>/comprovante/pdf/', views.criar_comprovante, name='pdf_comprovate'),
]

apps/core/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.Home.as_view(), name='indice'),
    path('sobre/', views.Sobre.as_view(), name='sobre'),
    path('servicos/', views.Servicos.as_view(), name='servicos'),
    path('contato/', views.Contato.as_view(), name='contato'),
    path('blog/', views.Blog.as_view(), name='blog'),
    path('redirecionar/', views.custom_login_redirect, name='redirecione'),
    path('painel/cadastrar/novo/paciente/', views.Cadastrar.as_view(), name='add'),
    path('painel/atualizar/<int:pk>/paciente/', views.AtualizarUser.as_view(), name='add_user'),
    path('painel/cadastrar/novo/funcionario/', views.CadastrarFuncionario.as_view(), name='add_funcionario'),
    path('painel/<int:id>/endereco/', views.EnderecoCad.as_view(), name='endereco'),
    path('painel/administrativo/', views.Painel.as_view(), name='painel'),
    path('painel/lista/pacientes/', views.Pacientes.as_view(), name='pacientes'),
    path('painel/lista/funcionarios/', views.Funcionarios.as_view(), name='funcionarios'),
    path('buscar/atendimento/paciente/', views.BuscarAtendimentoPaciente.as_view(), name='buscar_paciente'),
    path('painel/paciente/<int:pk>/perfil/', views.MostrarPerfil.as_view(), name='perfil'),
    path('paciente/atualizar/<int:pk>/senha/', views.AtualizarSenha.as_view(), name='senha_up'),
    path('painel/atualizar/<int:pk>/paciente/', views.AtualizarPerfil.as_view(), name='atualizar_perfil'),
    path('painel/atualizar/<int:pk>/endereco/', views.AtualizarEndereco.as_view(), name='atualizar_endereco'),
    path('buscar/', views.buscar_atendimento_paciente, name='busca'),
    path('paciente/buscar/', views.buscar_paciente, name='busca_paciente'),
    path('opcoes/<int:pk>/paciente/', views.OpcoesPaciente.as_view(), name='opcoes_paciente'),
    path('opcoes/atendimento/paciente/', views.BuscarOpcoesPaciente.as_view(), name='buscar_opcoes_paciente'),

]

apps/exame/urls.py
from django.urls import path
from . import views

app_name = 'exame'

urlpatterns = [
    path('adicionar/novo/exame/', views.ExameAdd.as_view(), name='exame_add'),
    path('novo/atendimento/<int:pk>/adicionar/', views.ExameAtendimentoADD.as_view(), name='exame_atendimento_add'),
    path('<int:pk>/atualizar/', views.ExameUp.as_view(), name='exame_up'),
    path('atendimento/<int:pk>/atualizar/', views.ExameAtendimentoUp.as_view(), name='exame_atendimento_update'),
    path('deletar/<int:pk>/', views.ExameDel.as_view(), name='exame_del'),
    path('atendimento/<int:pk>/deletar/', views.ExameAtendimentoDel.as_view(), name='exame_atendimento_del'),
    path('lista/', views.ExamesLista.as_view(), name='exame_list'),
    path('<str:data>/lista/', views.ExamesListaData.as_view(), name='exame_list_data'),
    path('<str:data>/etiquetas/', views.ExamesEtiquetas.as_view(), name='exame_etiquetas'),
    path('aguardando/terceirizados/lista/', views.ExamesListaTerceirizado.as_view(), name='exame_list_terceirizado'),
    path('realizados/<str:data>/', views.ExamesListaDataRealizados.as_view(), name='exame_realizados_data'),
    path('<int:pk>/informacoes/', views.ExameDetalhes.as_view(), name='exame_detail'),
    path('nova/referencias/<int:pk>/', views.ReferenciaADD.as_view(), name='referencias_add'),
    path('referencia/<int:pk>/atualizar/', views.ReferenciaUp.as_view(), name='referencia_update'),
    path('<int:pk>/referencia/deletar/', views.ReferenciaDEL.as_view(), name='referencia_del'),
    path('novo/fator/<int:pk>/adicionar/', views.FatorReferenciaADD.as_view(), name='fator_add'),
    path('fator/atualizar/<int:pk>/', views.FatorUp.as_view(), name='fator_up'),
    path('remover/<int:pk>/fator/', views.FatorDEL.as_view(), name='fator_del'),
    path('novo/valor/<int:pk>/adicionar/', views.ValorEsperadoADD.as_view(), name='padrao_add'),
    path('valor/atualizar/<int:pk>/', views.ValorUp.as_view(), name='valor_up'),
    path('valor/remover/<int:pk>/', views.ValorDEL.as_view(), name='valor_del'),

    # temporario
    path('mostrar/todos/lista/', views.ExamesTodosLista.as_view(), name='exame_todos_lista'),
    path('<int:pk>/pdf/', views.criar_laudo_medico, name='pdf'),
    path('preencher/<int:pk>/folha/', views.preencher_laudo_medico, name='preencher_pdf'),
    path('preencher/grupo/folha/', views.preencher_laudo, name='laudo_pdf'),

    # area medica #
    path('exame/<int:pk>/finalizar/', views.finalizar_exame, name='finalizar_exame'),
    path('area/restrita/<int:pk>/realizar/', views.ExameDetailView.as_view(), name='exame_medico_ver'),
    path('referencia/<int:pk>/salvar/', views.salvar_referencia, name='salvar_referencia'),

    path('terceirizado/area/restrita/<int:pk>/anexar/', views.ExameTerceirizado.as_view(), name='exame_medico_anexar'),
    path('pesquisar/', views.BuscarExame.as_view(), name='pesquisar_exame'),
    path('terceirizado/pesquisar/', views.BuscarExameterceirizado.as_view(), name='pesquisar_exame_terceirizado'),
    path('buscar/exame/', views.buscar_exame, name='buscar_exame'),
    path('terceirizado/buscar/exame/', views.buscar_exame_terceirizado, name='buscar_exame_terceirizado'),
    path('imprimir/etiqueta/<int:pk>/', views.etiqueta_exame, name='etiqueta_exame'),
    path('etiquetas/impressas', views.etiquetas_de_exame, name='etiquetas'),
    #grupo
    path('add/grupo/', views.GrupoCreate.as_view(), name='add_grupo'),
    path('data/grupo/<str:data>/', views.ExamesGrupoData.as_view(), name='grupo_data'),
]

gens/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace='inicio')),
    path('exame/', include('apps.exame.urls', namespace='exame')),
    path('agenda/', include('apps.agenda.urls', namespace='agenda')),
    path('atendimento/', include('apps.atendimento.urls', namespace='atendimento')),
    path('accounts/', include('django.contrib.auth.urls'),),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.contrib.auth.models import User
from django.db import models
from cpf_field.models import CPFField
from stdimage import StdImageField


class Usuario(models.Model):
    SEXO = [
        ('M', 'Masculino'),
        ('F', 'Feminino'),
    ]
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    nome = models.CharField(verbose_name='Nome', max_length=155)
    assinatura = StdImageField(upload_to='Imagens/Logo',
                                variations={'thumbnail': {'width': 300, 'height': 300}},
                                null=True, blank=True,
                                delete_orphans=True)
    cpf = models.CharField(verbose_name='CPF', max_length=15, blank=True, null=True)
    rg = models.CharField(verbose_name='RG', max_length=25, blank=True, null=True)
    sexo = models.CharField(verbose_name='Sexo', max_length=20, choices=SEXO)
    telefone = models.CharField(verbose_name='Telefone', max_length=20)
    data_nascimento = models.CharField(verbose_name='Data de Nascimento', max_length=50)
    cadastrado = models.DateTimeField(auto_now_add=True)
    atualizado = models.DateTimeField(auto_now=True)
    funcionario = models.BooleanField(verbose_name='Funcionário?', default=False)
    adm = models.BooleanField(verbose_name='Administrador?', default=False)
    doutor = models.BooleanField(verbose_name='Bio_Médico(a)?', default=False)
    paciente = models.BooleanField(verbose_name='Paciente?', default=False)
    status = models.BooleanField(verbose_name='Status', default=True)


    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'


class Endereco(models.Model):
    pessoa = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    rua = models.CharField(verbose_name='Rua', max_length=100)
    numero = models.CharField(verbose_name='Número', max_length=20, null=True, blank=True)
    complemento = models.CharField(verbose_name='Complemento', max_length=200, blank=True, null=True)
    bairro = models.CharField(verbose_name='Bairro', max_length=100)
    cep = models.CharField(verbose_name='Cep', max_length=10, blank=True)
    cidade = models.CharField(verbose_name='Cidade', max_length=100, blank=True)
    estado = models.CharField(verbose_name='Estado', max_length=30, blank=True)

    def __str__(self):
        return self.rua

    class Meta:
        verbose_name = 'Endereço'
        verbose_name_plural = 'Endereços'

apps/core/forms.py
from django import forms
from django.core.exceptions import ValidationError

from apps.core.models import Usuario, Endereco


class CriarUsuarioForm(forms.ModelForm):
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput(attrs={'placeholder': 'Senha', 'class': 'custom-text form-control', 'autocomplete': 'off'}))
    password2 = forms.CharField(label='Confirmar Senha', widget=forms.PasswordInput(attrs={'placeholder': 'Repetir Senha', 'class': 'custom-text form-control', 'autocomplete': 'off'}))

    class Meta:
        model = Usuario
        fields = ('nome', 'cpf', 'rg', 'sexo', 'data_nascimento', 'telefone')

        widgets = {
             'nome': forms.TextInput(attrs={'placeholder': 'Nome Completo', 'class': 'custom-text form-control'}),
             'cpf': forms.TextInput(attrs={'placeholder': '000.000.000-00', 'class': 'custom-text form-control'}),
             'telefone': forms.TextInput(attrs={'placeholder': '(88) 9 9999-9999', 'class': 'custom-text form-control'}),
             'rg': forms.TextInput(attrs={'class': 'custom-text form-control'}),
             'sexo': forms.Select(attrs={'class': 'custom-select form-control'}),
             'data_nascimento': forms.TextInput(attrs={'placeholder': 'dd/mm/aaaa', 'class': 'custom-text form-control', 'autocomplete': 'off'}),
        }

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Senhas não coincidem.")
        return password2


class CriarFuncionarioForm(forms.ModelForm):
    usuario = forms.CharField(label='Usuário', widget=forms.TextInput(attrs={'placeholder': 'Usuário', 'class': 'custom-text form-control', 'autocomplete': 'off'}))
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput(attrs={'placeholder': 'Senha', 'class': 'custom-text form-control', 'autocomplete': 'off'}))
    password2 = forms.CharField(label='Confirmar Senha', widget=forms.PasswordInput(attrs={'placeholder': 'Repetir Senha', 'class': 'custom-text form-control', 'autocomplete': 'off'}))

    class Meta:
        model = Usuario
        fields = ('nome', 'cpf', 'rg', 'sexo', 'data_nascimento', 'telefone', 'funcionario', 'adm', 'doutor' )

        widgets = {
             'nome': forms.TextInput(attrs={'placeholder': 'Nome Completo', 'class': 'custom-text form-control'}),
             'cpf': forms.TextInput(attrs={'placeholder': '000.000.000-00', 'class': 'custom-text form-control'}),
             'telefone': forms.TextInput(attrs={'placeholder': '(88) 9 9999-9999', 'class': 'custom-text form-control'}),
             'rg': forms.TextInput(attrs={'class': 'custom-text form-control'}),
             'sexo': forms.Select(attrs={'class': 'custom-select form-control'}),
             'data_nascimento': forms.TextInput(attrs={'placeholder': 'dd/mm/aaaa', 'class': 'custom-text form-control', 'autocomplete': 'off'}),
        }

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Senhas não coincidem.")
        return password2


class EnderecoForm(forms.ModelForm):
    class Meta:
        model = Endereco
        fields = ('rua', 'numero', 'complemento', 'bairro', 'cep', 'cidade', 'estado')


class AtualizarUsuarioForm(forms.ModelForm):
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput(attrs={'placeholder': 'Senha', 'class': 'custom-text form-control', 'autocomplete': 'off'}))
    password2 = forms.CharField(label='Confirmar Senha', widget=forms.PasswordInput(attrs={'placeholder': 'Repetir Senha', 'class': 'custom-text form-control', 'autocomplete': 'off'}))

    class Meta:
        model = Usuario
        fields = ('cpf',)

        widgets = {
            'cpf': forms.TextInput(attrs={'placeholder': '000.000.000-00', 'class': 'custom-text form-control'}),
            }

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Senhas não coincidem.")
        return password2

apps/core/templates/core/atualizar_senha.html
{% extends 'padrao/painel.html' %}
{% load static %}
{% load bootstrap4 %}
{% block titulo %}
Gen's | Atualizar Senha
{% endblock %}
{% block estilo %}
{{block.super}}
<style>
    .form-control:focus {
    color: #000;
    background-color: #ffffff;
    border-color: #4cb061;
    outline: 0
}
</style>
{% endblock %}
{% block trilha %}
<h4 class="h4 mb-0 text-success text-uppercase font-weight-bold">{{paciente}}</h4>
{% endblock %}
{% block conteudo %}
<div class="row">
    <div class="col col-mb-12">
        <div class="card mb-4">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <hr>
                    <div class="row">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-success btn-block">Atualizar Senha</button>
                        </div>
                        <div class="col-md-6">
                            <a href="{% url 'home:perfil' pk=paciente.pk %}" type="submit" class="btn btn-danger btn-block">Voltar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/core/templates/core/painel1.html
{% extends 'padrao/painel.html' %}
{% load static %}
{% load bootstrap4 %}
{% block titulo %}
Gen's | Painel Administrativo
{% endblock %}
{% block trilha %}
{% endblock %}

{% block estilo %}
{{block.super}}
 <style>
    a.text-secondary:hover {
      color: #28a745 !important;
    }
  </style>
{% endblock %}
{% block conteudo %}
<div class="row mb-3">
    <!-- teste -->
    <div class="col-md-12">
    <div class="card mb-4">
        <div class="card-body">
            <div class="row">
                {% if user.is_authenticated and user.usuario.funcionario or user.usuario.adm %}
                <div class="col-xl-4 col-md-6 mb-4 mt-3">
                    <a href="{% url 'agenda:pesquisar_paciente' %}" class="text-decoration-none text-secondary font-weight-bold">
                        <ul class="list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            Adicionar a fila
                            <span class="badge badge-success badge-pill">
                                <i class="bi bi-person-add text-white"></i>
                            </span>
                        </li>
                    </ul>
                    </a>
                </div>
                <div class="col-xl-4 col-md-6 mb-4 mt-3">
                    <a href="{% url 'agenda:ordem_chegada_lista' %}" class="text-decoration-none text-secondary font-weight-bold">
                        <ul class="list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            Aguardando na fila
                            <span class="badge badge-success badge-pill">{{fila_aguardando}}</span>
                        </li>
                    </ul>
                    </a>
                </div>
                <div class="col-xl-4 col-md-6 mb-4 mt-3">
                    <a href="{% url 'agenda:ordem_chegada_lista' %}" class="text-decoration-none text-secondary font-weight-bold">
                        <ul class="list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            Pacientes atendidos
                            <span class="badge badge-success badge-pill">{{fila_atendido}}</span>
                        </li>
                    </ul>
                    </a>
                </div>
                {% endif %}
                {% if user.is_authenticated and user.usuario.doutor or user.usuario.adm %}
                <div class="col-xl-4 col-md-6 mb-4 mt-3">
                 <a href="{% url 'exame:pesquisar_exame' %}" class="text-decoration-none text-secondary font-weight-bold">
                     <ul class="list-group custom-list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div>
                                <span class="custom-title font-weight-bold">Pesquisar Exame</span>
                                <div class="mt-2 mb-0 text-xs">
                                     <span class="text-secondary mr-2 font-weight-light font-italic">Pesquisar pelo número do exame</span>
                                </div>
                            </div>
                            <span class="badge badge-success badge-pill"><i class="bi bi-search"></i></span>
                        </li>
                    </ul>
                 </a>
                </div>
                <div class="col-xl-4 col-md-6 mb-4 mt-3">
                  <a href="{% url 'exame:exame_realizados_data' data=data %}" class="text-decoration-none text-secondary font-weight-bold">
                    <ul class="list-group custom-list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div>
                                <span class="custom-title font-weight-bold">Exames</span>
                                <div class="mt-2 mb-0 text-muted text-xs">
                                     <span class="text-secondary mr-2 font-weight-light font-italic">{{data}}</span>
                                </div>
                            </div>
                            <span class="badge badge-success badge-pill">{{qtd_exames_realizados}}</span>
                        </li>
                    </ul>
                  </a>
                </div>
                <div class="col-xl-4 col-md-6 mb-4 mt-3">
                  <a href="{% url 'exame:exame_list_data' data=data %}" class="text-decoration-none text-secondary font-weight-bold">
                    <ul class="list-group custom-list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div>
                                <span class="custom-title font-weight-bold">Exames (Aguardando)</span>
                                <div class="mt-2 mb-0 text-muted text-xs">
                                     <span class="text-secondary mr-2 font-weight-light font-italic">{{data}}</span>
                                </div>
                            </div>
                            <span class="badge badge-success badge-pill">{{qtd_exames}}</span>
                        </li>
                    </ul>
                  </a>
                </div>
                <div class="col-xl-4 col-md-6 mb-4 mt-3">
                 <a href="{% url 'exame:pesquisar_exame_terceirizado' %}" class="text-decoration-none text-secondary font-weight-bold">
                     <ul class="list-group custom-list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div>
                                <span class="custom-title font-weight-bold">Pesquisar Exame Terceirizado</span>
                                <div class="mt-2 mb-0 text-xs">
                                     <span class="text-secondary mr-2 font-weight-light font-italic">Pesquisar pelo número do exame</span>
                                </div>
                            </div>
                            <span class="badge badge-success badge-pill"><i class="bi bi-search"></i></span>
                        </li>
                    </ul>
                 </a>
                </div>
                <div class="col-xl-4 col-md-6 mb-4 mt-3">
                  <a href="{% url 'exame:grupo_data' data=data %}" class="text-decoration-none text-secondary font-weight-bold">
                    <ul class="list-group custom-list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div>
                                <span class="custom-title font-weight-bold">Grupos Exames</span>
                                <div class="mt-2 mb-0 text-muted text-xs">
                                     <span class="text-secondary mr-2 font-weight-light font-italic">{{data}}</span>
                                </div>
                            </div>
                            <span class="badge badge-success badge-pill">{{qtd_exames_realizados}}</span>
                        </li>
                    </ul>
                  </a>
                </div>
                <div class="col-xl-4 col-md-6 mb-4 mt-3">
                  <a href="{% url 'exame:exame_etiquetas' data=data %}" class="text-decoration-none text-secondary font-weight-bold">
                    <ul class="list-group custom-list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div>
                                <span class="custom-title font-weight-bold">Etiquetas de Exames</span>
                                <div class="mt-2 mb-0 text-muted text-xs">
                                     <span class="text-secondary mr-2 font-weight-light font-italic">{{data}}</span>
                                </div>
                            </div>
                            <span class="badge badge-success badge-pill">{{qtd_exames}}</span>
                        </li>
                    </ul>
                  </a>
                </div>
                {% endif %}
                {% if user.is_authenticated and user.usuario.paciente or user.usuario.adm %}
                <div class="col-xl-4 col-md-6 mb-4 mt-3">
                  <a href="{% url 'atendimento:relatorio_diario' %}" class="text-decoration-none text-secondary font-weight-bold">
                    <ul class="list-group custom-list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div>
                                <span class="custom-title font-weight-bold">Atendimento(s) Diário</span>
                                <div class="mt-2 mb-0 text-muted text-xs">
                                     <span class="text-secondary mr-2">{{data}}</span>
                                </div>
                            </div>
                            <span class="badge badge-success badge-pill">{{ated_diario}}</span>
                        </li>
                    </ul>
                  </a>
                </div>
                <div class="col-xl-4 col-md-6 mb-4 mt-3">
                  <a href="{% url 'atendimento:relatorio_semanal' %}" class="text-decoration-none text-secondary font-weight-bold">
                    <ul class="list-group custom-list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div>
                                <span class="custom-title font-weight-bold">Atendimento(s) Semanal</span>
                                <div class="mt-2 mb-0 text-muted text-xs">
                                     <span class="text-secondary mr-2">({{inicio|date:"d/m/Y"}} a {{final|date:"d/m/Y"}})</span>
                                </div>

                            </div>
                            <span class="badge badge-success badge-pill">{{atendimentos}}</span>
                        </li>
                    </ul>
                  </a>
                </div>
                <div class="col-xl-4 col-md-6 mb-4 mt-3">
                    <ul class="list-group custom-list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div>
                                <span class="custom-title font-weight-bold">Atendimento(s) Mensal</span>
                                <div class="mt-2 mb-0 text-muted text-xs">
                                     <span class="text-secondary mr-2">({{primeiro|date:"d/m/Y"}} a {{ultimo|date:"d/m/Y"}})</span>
                                </div>
                            </div>
                            <span class="badge badge-success badge-pill">{{atendimentos_mes}}</span>
                        </li>
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}